"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-17 16:59:36.909090
"""
from alembic import op
import sqlalchemy as sa

from app.db.reference_data import PREDEFINED_DRONES, PREDICTION_MODELS

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('battery_capacity_wh', sa.Float(), nullable=False),
    sa.Column('payload_capacity_kg', sa.Float(), nullable=False),
    sa.Column('is_predefined', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('battery_capacity_wh > 0', name='ck_drone_battery_positive'),
    sa.CheckConstraint('payload_capacity_kg > 0', name='ck_drone_payload_positive'),
    sa.CheckConstraint('weight_kg > 0', name='ck_drone_weight_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.CheckConstraint('tier IN (1, 2)', name='ck_prediction_model_tier'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('mission_leg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('duration_min', sa.Float(), nullable=False),
    sa.Column('altitude_m', sa.Float(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('payload_kg', sa.Float(), nullable=False),
    sa.CheckConstraint('altitude_m > 0', name='ck_leg_altitude_positive'),
    sa.CheckConstraint('distance_km > 0', name='ck_leg_distance_positive'),
    sa.CheckConstraint('duration_min > 0', name='ck_leg_duration_positive'),
    sa.CheckConstraint('payload_kg > 0', name='ck_leg_payload_positive'),
    sa.ForeignKeyConstraint(['mission_id'], ['mission.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_model_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('dataset_source', sa.String(length=20), nullable=False),
    sa.Column('dataset_name', sa.String(length=200), nullable=False),
    sa.Column('feature_set', sa.JSON(), nullable=False),
    sa.Column('feature_ranges', sa.JSON(), nullable=False),
    sa.Column('hyperparameters', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('artifact_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("dataset_source IN ('team', 'custom-uploaded')", name='ck_model_version_dataset_source'),
    sa.ForeignKeyConstraint(['prediction_model_id'], ['prediction_model.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prediction_model_id', 'version', name='uq_model_version')
    )
    op.create_table('wind_speed_condition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('wind_speed_ms', sa.Float(), nullable=False),
    sa.CheckConstraint('wind_speed_ms >= 0', name='ck_wind_speed_non_negative'),
    sa.ForeignKeyConstraint(['mission_id'], ['mission.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mission_id')
    )
    op.create_table('scenario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('drone_id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['drone_id'], ['drone.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['mission.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('drone_id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.Column('leg_results', sa.JSON(), nullable=False),
    sa.Column('total_energy_wh', sa.Float(), nullable=False),
    sa.Column('battery_capacity_wh', sa.Float(), nullable=False),
    sa.Column('safety_margin', sa.Float(), nullable=False),
    sa.Column('usable_capacity_wh', sa.Float(), nullable=False),
    sa.Column('margin_wh', sa.Float(), nullable=False),
    sa.Column('feasibility', sa.Boolean(), nullable=False),
    sa.Column('reduced_confidence', sa.Boolean(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['drone_id'], ['drone.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mission_id'], ['mission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_version.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comparison_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comparison_id', sa.String(length=36), nullable=False),
    sa.Column('simulation_result_id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('drone_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['drone_id'], ['drone.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mission_id'], ['mission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['simulation_result_id'], ['simulation_result.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparison_result_comparison_id'), 'comparison_result', ['comparison_id'], unique=False)
    # ### end Alembic commands ###

    # Reference data (predefined drones are read-only, SRS §3.2.1). Explicit ids, so bump sequences.
    meta = sa.MetaData()
    meta.reflect(bind=op.get_bind(), only=("prediction_model", "drone"))
    op.bulk_insert(meta.tables["prediction_model"], PREDICTION_MODELS)
    op.bulk_insert(meta.tables["drone"], PREDEFINED_DRONES)
    for table in ("prediction_model", "drone"):
        op.execute(f"SELECT setval(pg_get_serial_sequence('{table}', 'id'), (SELECT MAX(id) FROM {table}))")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comparison_result_comparison_id'), table_name='comparison_result')
    op.drop_table('comparison_result')
    op.drop_table('simulation_result')
    op.drop_table('scenario')
    op.drop_table('wind_speed_condition')
    op.drop_table('model_version')
    op.drop_table('mission_leg')
    op.drop_table('prediction_model')
    op.drop_table('mission')
    op.drop_table('drone')
    # ### end Alembic commands ###
